### ISSUE TITLE
Indentation missing in snippets

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidtypo3org#29] opened 2015-11-08 19:24 UTC
Snippets miss the whitespace indentation:

Compare
> https://fluidtypo3.org/library/code-examples.html?tx_fluidshare_display[gist]=26&tx_fluidshare_display[action]=display&tx_fluidshare_display[controller]=Gist&cHash=102b227860b7ae0193d492073ae55688

with the original gist

> https://gist.github.com/uweschmelzer/816afad27137179b8c5c#file-simple-language-switcher

Moved from https://github.com/FluidTYPO3/documentation/issues/56

**Comment by cweiske** [comment] 2015-11-10 06:52
I'd call it a bug, but in this case fixing the bug is also enhancing the experience.

**Comment by xf-** [comment] 2015-11-10 08:28
For me it is a enhancement. currently it works, indents are smaller and it isn't important to. LTS fixes and other issues are more important.

**Comment by cweiske** [comment] 2015-11-10 08:30
If "smaller" means "non-existing", then you are right:
![2015-11-10 smaller indents](https://cloud.githubusercontent.com/assets/59036/11057704/90f86600-878d-11e5-93e9-433837941a18.png)

**Comment by cedricziel** [comment] 2015-11-10 08:33
Hi Christian,

be assured that I consider this important and a bug. Can you help us improve the rendering?

Cheers!
Cedric

**Comment by cweiske** [comment] 2015-11-10 08:54
The gitst's downloaded json is stored at
> https://fluidtypo3.org/typo3temp/fluidshare-gist-c220ff6da967fb65250ac4b09a93ef266c3b961c.json
and it does contain the indentation whitespace (tabs in this case). So it's probably a rendering problem.

The output uses `<f:format.raw>`; see https://github.com/FluidTYPO3/fluidshare/blob/master/Resources/Private/Templates/Gist/Display.html
I can confirm that this does not remove tabs on my machine.

Maybe you have a tidy plugin installed on your web server, or set typo3 to tidy up html?

**Comment by NamelessCoder** [comment] 2016-06-12 15:21
Closing (4/4), copied to internal add/avoid/fix list for coming web site overhaul. Thanks for reporting!

On a side note: this may be caused by using CloudFlare on the site. As part of our overhaul we'll go through and evaluate current CloudFlare usage - and whether to even use CloudFlare in the future or go the letsencrypt etc. way.

If either one of you knows what does this and can point to some CloudFlare flag I'll happily change it right away as a quick fix - but we'll also be evaluating our CF usage in general, later ;)

**Closed by NamelessCoder** 2016-06-12 15:21 UTC
Labels: bug
